apiVersion: v1
kind: Service
metadata:
  name: broker-external
  namespace: knative-eventing
spec:
  selector:
    app: kafka-broker-receiver
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  - name: https
    port: 443
    protocol: TCP
    targetPort: 8443
  - name: http-container
    port: 8080
    protocol: TCP
    targetPort: 8080
  type: LoadBalancer