apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaMirrorMaker2
metadata:
  name: my-mirror-maker
  namespace: knative-eventing
spec:
  version: 3.5.1
  replicas: 1
  connectCluster: "my-cluster2"
  clusters:
  - alias: "my-cluster"
    bootstrapServers: my-cluster-kafka-bootstrap:9092
  - alias: "my-cluster2"
    bootstrapServers: my-cluster2-kafka-bootstrap:9092
    config:
      config.storage.replication.factor: -1
      offset.storage.replication.factor: -1
      status.storage.replication.factor: -1
  mirrors:
  - sourceCluster: "my-cluster"
    targetCluster: "my-cluster2"
    sourceConnector:
      tasksMax: 1
      config:
        replication.factor: -1
        offset-syncs.topic.replication.factor: -1
        sync.topic.acls.enabled: "false"
    checkpointConnector:
      tasksMax: 1
      config:
        checkpoints.topic.replication.factor: -1
    topicsPattern: ".*"
    groupsPattern: ".*"
