apiVersion: sources.knative.dev/v1beta1
kind: KafkaSource
metadata:
  name: kafka-source1
  namespace: knative-eventing
spec:
  consumerGroup: default
  bootstrapServers:
    - my-cluster-kafka-bootstrap:9092
  topics:
    - my-topic
  resources:
    limits:
      cpu: 250m
      memory: 512Mi
    requests:
      cpu: 250m
      memory: 512Mi
  sink:
    ref:
      apiVersion: v1
      kind: Service
      name: echo-service
    uri: /echo/
